### ISSUE TITLE
Visitor inefficiencies

### ISSUE THREAD

**Issue by regexident** [pksunkara/cargo-up#6]
In its current form the visitation is still rather inefficient:

Regardless of whether a program actually overrides a given `fn visit_*` method the given node will be cloned and passed to the visitor. Every single node in the crate's source code. Every single one. In a large code base this might end up in hundreds of thousands of clones.

This is happening due to the eager `node.clone()` in 

```rust
match self.kind() {
    $(SyntaxKind::$kind => visitor.$method(
        &ast::$node::cast(node.clone()).expect(INTERNAL_ERR),
        semantics,
    ),)*
    _ => {},
};
```

One possible way to improve this is to change

```rust
$(fn $method(&mut self, _node: &ast::$node) {})*
```

to

```rust
$(fn $method<T>(&mut self, _node: &SyntaxNode, _materialize: T)
where
    T: FnOnce(&SyntaxNode) -> ast::$node
{})*
```

and

```rust
$(SyntaxKind::$kind => visitor.$method(
    &ast::$node::cast(node.clone()).expect(INTERNAL_ERR),
),)*
```

to

```rust
$(SyntaxKind::$kind => visitor.$method(
    self,
    |node| ast::$node::cast(node.clone()).expect(INTERNAL_ERR),
),)*
```

Which effectively moves the `.clone()` and corresponding `::cast(...)` into a lazily evaluated closure.

As such a method like this

```rust
fn visit_struct(&mut self, _node: &Struct) {}
```

would become

```rust
fn visit_struct<T>(&mut self, _node: &SyntaxNode, _materialize: T)
where
    T: FnOnce(&SyntaxNode) -> ast::Struct
{}
```

The user would then have to explicitly materialize the node like so:

```rust
fn visit_struct<T>(&mut self, node: &SyntaxNode, materialize: T)
where
    T: FnOnce(&SyntaxNode) -> ast::Struct
{
    let struct_node = materialize(node);
    // ...
}
```

This way unless the user explicitly materializes the node as a typed variant no cloning is performed.

This also has the additional benefit of passing ownership to the method, avoiding more clones, if the the user needs to keep the object.

This of course comes at the cost of a slightly more complex API. I'd argue though that it's worth the

---

What do you think about this, @pksunkara?

**Comment by regexident** [comment]
Another alternative would be to remove the typed `fn visit_*` altogether, as they are causing the issue to begin with. But then not much would be left of the trait/crate. 🤔

**Comment by pksunkara** [comment]
I too was afraid of the `clone` when I started working on this. Then, I investigated and found this little definition in `rowan/src/cursor.rs`:

```rust
#[derive(Debug, Clone)]
pub struct SyntaxNode(Rc<NodeData>);
```

And all the ast nodes are just structs on `rowan::SyntaxNode` on this. So, the cloning was really just cloning a pointer at the end.

Were you noticing any performance issues? Do you think we should still address this?

**Comment by regexident** [comment]
Apart from the `.clone()` the `::cast(&node)` was another possible issue.

I say was, as it is apparently just as efficient as the clone. This is how basically all cast implementations look like:

```rust
impl AstNode for Struct {
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == STRUCT
    }

    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }

    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
```

A quick benchmark confirms this:

```rust
// With clone + cast:
// Time elapsed: 23.810835ms
// Number of nodes is: 36992

// Without clone + cast:
// Time elapsed: 23.331632ms
// Number of nodes is: 36974
```

So yeah, closing this for obvious reasons.

**Comment by pksunkara** [comment]
Thanks for confirming it. I haven't benchmarked it before. 🙏

**Comment by regexident** [comment]
Also just to clarify the difference in node count during benchmarks:

I was running the visitor on the project itself, hence the difference between versions.
